### ISSUE TITLE
Pose format continues to cause failures

### ISSUE THREAD

**Issue by alexander-sung** [DFKI-NI/mobipick#4]
The pose format with the quaternion coordinates in order `(w, x, y, z)` continues to cause failures for Mobipick applications. An essential problem is that its float[7] format is easily converted into a geometry_msgs.msg.Pose the wrong way (see http://docs.ros.org/en/noetic/api/geometry_msgs/html/msg/Quaternion.html) without it being noticed. The comment in the config file obviously does not suffice.

I forgot why exactly why we still keep it this way (reason was like: "it is used somewhere like this"), so I'll adjust our mobipick_labs code once more to this pose format, this time in the symbolic_fact_generation. Again, I recommend to switch to the ROS format. We can even use the format `([px, py, pz], [qx, qy, qz, qw])` to be sure to break things where updates are needed.

For your information, @mintar, @sebastianstock, @marcvinci.

**Comment by alexander-sung** [comment]
Note: A workaround is needed for mobipick_labs plus its dependencies at three places now, which can be found by, e.g., `rg "\[4:\]"` in the workspace directory.

**Comment by mintar** [comment]
> I forgot why exactly why we still keep it this way

The reason was simply because `rosparam_shortcuts` enumerates the geometry_msgs/Pose message fields in alphabetical order (position.x, position.y, position.z, orientation.w, orientation.x, orientation.y, orientation.z) and expects the list of floats to be in the same order:

https://github.com/DFKI-NI/mobipick/blob/ef3ca14c61dba9c723f8e8dab25fb5ee89733191/mobipick_pick_n_place/src/mobipick_pick_n_place.cpp#L525-L526

This is really the fault of `rosparam_shortcuts`; it shouldn't read the fields in alphabetical order, but in the order that they were defined in the ROS message (x, y, z, w).

> Again, I recommend to switch to the ROS format.

Yes, 100% agree! It's much less error-prone to stick to the ROS standards everywhere (for quaternions: x, y, z, w). That means complicating reading the parameters in `mobipick_pick_n_place.cpp` a little bit, but I think it's worth it.

**Comment by mintar** [comment]
> We can even use the format `([px, py, pz], [qx, qy, qz, qw])` to be sure to break things where updates are needed.

Yes, I like that. Also, it's more readable in my opinion.

BTW, I just checked the code in `rosparam_shortcuts`, and the reason why they do it like this isn't because of alphabetical ordering, but because they use Eigen as an intermediate step, and the ordering in Eigen::Quaterniond is qw, qx, qy, qz. Anyhow, we should stick to ROS standards, not Eigen standards.

**Comment by alexander-sung** [comment]
Yes, I remember you pointing me to Eigen before! That's the reason we left it this way because even in rosparam that standard is used. By the way, I found something interesting in the Eigen library itself: https://gitlab.com/libeigen/eigen/-/blob/master/Eigen/src/Geometry/Quaternion.h#L295. The interface has a different order than the internal storage, even for Eigen's quaternion. We can be assured that this problem will continue to amaze users also in the future.

**Comment by mintar** [comment]
> even in rosparam that standard is used

Do you mean rosparam_shortcuts? That's no official library, just some third-party addon.

> By the way, I found something interesting in the Eigen library itself: [...]

Nice find, I didn't know that!

**Comment by alexander-sung** [comment]
Oh okay. Then it's really time to improve this. I'll handle it but after some other merges because of the many different places this change will affect.

**Comment by alexander-sung** [comment]
Solved in internal mobipick repository, push upcoming.
